In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
np.random.shuffle(arr)
print(arr)

[5 6 1 3 4 2]


In [3]:
arr=np.array([1,2,3,4,5,6])
np.random.shuffle(arr)
print(arr)

[2 1 6 5 4 3]


In [4]:
arr1=np.array([1,2,2,3,3,4,5])
x=np.resize(arr1,(2,2,2))
print(np.ravel(x,order="A"))

[1 2 2 3 3 4 5 1]


In [ ]:
matrix=np.matrix([[1,2,3],[4,5,6]])
print(matrix)
print(type(matrix))


[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [11]:
var1=np.matrix([[1,2],[3,4]])
var2=np.matrix([[5,6],[7,8]])
print(var1.dot(var2))


[[19 22]
 [43 50]]


In [ ]:
var1=np.matrix([[1,2],[3,4]])
print(np.transpose(var1))
print(var1.T)#another way to transpose matrix

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [16]:
var1=np.matrix([[1,2],[3,4]])
print(np.swapaxes(var1,0,1))
print()
print(np.swapaxes(var1,1,0))


[[1 3]
 [2 4]]

[[1 3]
 [2 4]]


In [26]:
var1=np.matrix([[1,2,7],[3,4,5],[1,2,3]])
print(np.linalg.inv(var1))
print()
print(np.linalg.matrix_power(var1,2))#for power of matrix
print()
print(np.linalg.det(var1))


[[ 0.25  1.   -2.25]
 [-0.5  -0.5   2.  ]
 [ 0.25 -0.   -0.25]]

[[14 24 38]
 [20 32 56]
 [10 16 26]]

8.000000000000002
